# Generated by Django 4.1.5 on 2024-04-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('suubcategory', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0)),
                ('priceone', models.FloatField(default=0)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
