# Generated by Django 4.1.5 on 2024-04-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('phone', models.IntegerField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('subject', models.CharField(max_length=155)),
                ('company', models.CharField(max_length=155)),
                ('textarea', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
