# Generated by Django 4.1.5 on 2024-04-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_corporate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
