# Generated by Django 4.1.5 on 2024-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_larq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='href',
            field=models.CharField(default='exit', max_length=155),
            preserve_default=False,
        ),
    ]
