# Generated by Django 4.1.5 on 2024-04-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemsJson', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('username', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip', models.CharField(max_length=300)),
                ('checkbox1', models.CharField(max_length=300)),
                ('paymentMethod', models.CharField(max_length=300)),
                ('cardname', models.CharField(max_length=300)),
                ('cardnumber', models.CharField(max_length=300)),
                ('expiration', models.CharField(max_length=300)),
                ('cvv', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
