# Generated by Django 4.1.5 on 2024-04-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
