# Generated by Django 4.1.5 on 2024-05-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_orders_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=155)),
                ('repeatpassword', models.CharField(max_length=155)),
                ('date', models.DateField()),
            ],
        ),
    ]
